### ISSUE TITLE
Specification of absolute paths

### ISSUE THREAD

**Issue by dparkins** [daniel-muthukrishna/SNClassifying_Pre-alpha#1]
It would be better if this code didn't have the paths to different files hard-coded in. Maybe you could use the following commands to find the local path, and so locate the files you need: 
`import os
print os.getcwd()`

**Comment by daniel-muthukrishna** [comment]
This issue should be fixed in the latest commit. Let me know if it is

**Comment by dparkins** [comment]
Yes, it works very well, straight from the repo.
![sn_classifier](https://cloud.githubusercontent.com/assets/3622802/19101004/62fcaed6-8b07-11e6-9769-e6ae00abb4cb.jpg)
