### ISSUE TITLE
Known z box too small to see numbers on MacOSX

### ISSUE THREAD

**Issue by dparkins** [daniel-muthukrishna/SNClassifying_Pre-alpha#2]
![sn_classifier_problem](https://cloud.githubusercontent.com/assets/3622802/18977960/394db098-8702-11e6-94c2-247dadfd352b.jpg)

**Comment by daniel-muthukrishna** [comment]
This should also be fixed. Let me know

**Comment by dparkins** [comment]
Yes, it looks fine now.
