### ISSUE TITLE
Error when running without knownz

### ISSUE THREAD

**Issue by dparkins** [daniel-muthukrishna/SNClassifying_Pre-alpha#3]
When I run without a known redshift, I get the following error

> Traceback (most recent call last):
>   File "main.py", line 216, in list_item_clicked
>     self.plot_best_matches()
>   File "main.py", line 223, in plot_best_matches
>     wave_redshifted = self.wave \* ((self.plotZ-self.knownZ) + 1)
> AttributeError: 'MainApp' object has no attribute 'knownZ'

**Comment by daniel-muthukrishna** [comment]
This should be fixed. However, note that the results without a known redshift should not be considered reliable at this stage. Also note that it can take up to 3 minutes to finish running.

**Comment by dparkins** [comment]
Thanks, I no longer get that error
